### PR TITLE
trigger chdir events 

### LINKED ISSUE #1: vox activation not working
This xontrib is useful with terminals like `kitty` which don't remember the last session. But when this xontrib is loaded, my custom script to activate the vox environment based on the current location is not getting fired. I suspect it is because the `events.on_cd` is not fired.

### PR DESCRIPTION
**Pull request by jnoortheen**
closes #1

### CODE REVIEW

**Comment by anki-code** [comment]
@jnoortheen thanks! Is there a way to avoid using xsh? Because it will not compiled to `pyc` it have an overhead for xonsh parsing and compiling. 

As I see you need xsh only for `cd @(newdir)`. It will be great to do it with pure python.

**Comment by jnoortheen** [comment]
I don't know any other way to trigger `events.on_chdir` .

**Comment by anki-code** [comment]
May be it will help:
```
__xonsh__.builtins.events.on_chdir.fire(olddir='/old',newdir='/new')
```

**Comment by jnoortheen** [comment]
putting the dirs manually feels off. Is there any other way? to run xonsh's subprocess mode.

**Comment by anki-code** [comment]
Yep:
```python
__xonsh__.subproc_captured_stdout(['cd', '/tmp'])
```

**Comment by anki-code** [comment]
Great! Thanks @jnoortheen !

**Pull request merged**
